### ISSUE TITLE
Data Mismatch

### ISSUE THREAD

**Issue by jvandevalk** [OpenDRR/riskprofiler#44]
When I zoom into neighbourhoods, the number of people that are highlighted (8), are different than the number of people on the graph (5 + 1 = 6). This seems consistent for many neighbourhoods not in the screenshot attached (10 vs 4, 31 vs 25, etc.)

![RP_ZoomIn](https://user-images.githubusercontent.com/103536301/175575819-cdb14d3a-0dd4-436c-9863-a745c62fc8fa.PNG)

**Comment by phil-evans** [comment]
@drotheram testing this out with the georgia strait scenario and Sauid 59007458, here:

![Screen Shot 2022-07-04 at 10 21 55 AM](https://user-images.githubusercontent.com/18401550/177164096-27a8680a-0320-4f8a-8aaf-c5eb8f8f59ad.png)
 
the rounded value on the map is 11 people, and the elasticsearch request for the 'building type' chart retrieves a total of 6 people:

![Screen Shot 2022-07-04 at 10 25 00 AM](https://user-images.githubusercontent.com/18401550/177164422-0483225b-6933-480c-aeff-fd72244cdd50.png)

and here's the full request object:

```json
{
	"aggs": {
		"0": {
			"terms": {
				"field": "properties.E_BldgTypeG.keyword",
				"order": { "1": "desc" },
				"size":100
			},
			"aggs": {
				"1": {
					"sum": {
						"field": "properties.sC_CasDayL1_b0"
					}
				}
			}
		}
	},
	"size": 0,
	"fields": [],
	"script_fields": {},
	"stored_fields": [ "*" ],
	"runtime_mappings": {},
	"_source": { "excludes": [] },
	"query": {
		"bool": {
			"must": [],
			"filter": [ {
				"bool": {
					"should": [ {
						"match_phrase": {
							"properties.Sauid.keyword": "59007458"
						}
					} ],
					"minimum_should_match": 1
				}
			} ],
			"should": [],
			"must_not": []
		}
	}
}
```

**Comment by phil-evans** [comment]
similarly this CSD shows 34 people but only pulls a total of 4 from elasticsearch:

![Screen Shot 2022-07-04 at 10 56 55 AM](https://user-images.githubusercontent.com/18401550/177169637-259de90e-e676-4683-8985-e1a1a93b6248.png)
![Screen Shot 2022-07-04 at 10 56 37 AM](https://user-images.githubusercontent.com/18401550/177169639-46c3212c-9426-4168-b515-7540580671f3.png)

**Comment by wkhchow** [comment]
Checking out from the postgis db side:

I think its rounding issue on the ES side??  people values are summed up building level to sauid level and all values are included, hence I think that is why we are seeing the discrepancy. I think this may have to warrant discussion on how to display the values as even fractional values are considered.

Looking at the sauid layer. The sauid 59007458 value has 10.78 which checks out
![image](https://user-images.githubusercontent.com/59062243/179082876-ceff26f2-2a3e-4b69-a43b-717fc6b6d0e0.png)


Looking at the building layer
26 records summing up the value checks out 10.78
rounding rounds to 10
![image](https://user-images.githubusercontent.com/59062243/179087541-b2f14800-949b-4ce5-8a72-0e9104cad6c2.png)




csd layer from above:
34.22 people
![image](https://user-images.githubusercontent.com/59062243/179086652-b5bd4969-6e09-4ac4-b316-27462b7c2b48.png)

building layer
1898 records sums up to 34.22 people
round values to 10
![image](https://user-images.githubusercontent.com/59062243/179087812-c07af62f-a467-45b4-b352-3e49a2261825.png)

**Comment by drotheram** [comment]
After some further investigation, I've determined that this is indeed a problem with the ElasticSearch sum aggregation not returning correct values. I checked this through a spot check of one Sauid but it seem fairly apparent that this is the issue. Here was my thought process: 

Step-1: 

Let's pick an Sauid in RiskProfiler for the 9.0 Scenario and confirm what @wkhchow and @phil-evans have already shown:
![Screen Shot 2022-08-25 at 2 54 34 PM](https://user-images.githubusercontent.com/7228960/186775856-ddabbb5b-dadc-4b6b-81e8-31faad167d1c.png)


Step-2: 
Now first let's just confirm that the vector tile is returning the same thing
![Screen Shot 2022-08-25 at 2 55 33 PM](https://user-images.githubusercontent.com/7228960/186776007-3ee45be4-5556-40b0-9400-a5be43c47b34.png)
Ok, good


Step-3a: 
Ok, let's check PostGIS, first we'll check the Sauid aggregation with this query:
`SELECT * FROM results_dsra_sim9p0_cascadiainterfacebestfault.dsra_sim9p0_cascadiainterfacebestfault_indicators_s
WHERE "Sauid"='59008199'; `
![Screen Shot 2022-08-25 at 2 57 29 PM](https://user-images.githubusercontent.com/7228960/186776286-d57f35c4-b54f-4c31-9724-ef2448c674f1.png)
Ok, this checks out and agrees with the vector tile


Step-3b: 
Now lets check the PostGIS building level aggregation:
`SELECT * FROM results_dsra_sim9p0_cascadiainterfacebestfault.dsra_sim9p0_cascadiainterfacebestfault_indicators_b
WHERE "Sauid"='59008199'; `
![Screen Shot 2022-08-25 at 3 00 40 PM](https://user-images.githubusercontent.com/7228960/186776626-9918cb08-2875-47ce-8788-da535f07a361.png)
Ok, so there's 69 values, and when we sum them up.... 
![Screen Shot 2022-08-25 at 3 01 29 PM](https://user-images.githubusercontent.com/7228960/186776729-1e2eb472-e954-4a15-99a6-589e28162c96.png)



Ok, so this means that the problem is somewhere on the ElasticSearch side:


Step-4a: 
So let's start querying ES, first lets check the Sauid index with this query:
GET opendrr_dsra_sim9p0_cascadiainterfacebestfault_indicators_s/_search?size=70
{
  "_source": {        
        "includes": ["properties.sCt_CasDayL1_b0"]
    },
  "query": {
    "match": {
      "properties.Sauid": 59008199
    }
  },
  "aggs": {
    "Sum sCt_CasDayL1_b0": {
      "sum": {
        "field": "properties.sCt_CasDayL1_b0"
      }
    }
  }
}

The response:
{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : 9.80514,
    "hits" : [
      {
        "_index" : "opendrr_dsra_sim9p0_cascadiainterfacebestfault_indicators_s_v1.4.2",
        "_type" : "_doc",
        "_id" : "J-1caoEBHgS-HUNeTFH9",
        "_score" : 9.80514,
        "_ignored" : [
          "properties.geom_poly.keyword"
        ],
        "_source" : {
          "properties" : {
            "sCt_CasDayL1_b0" : 79.655
          }
        }
      }
    ]
  },
  "aggregations" : {
    "Sum sCt_CasDayL1_b0" : {
      "value" : 79.65499877929688
    }
  }
}

Ok, only one record and the value and sum are consistent with both the database and the vector tile. But notice we have some anomalous floating point values, we might be on to something.

Step-4b: 

So now let's check the building level aggregation index with this query:
GET opendrr_dsra_sim9p0_cascadiainterfacebestfault_indicators_b/_search?size=70
{
  "_source": {        
        "includes": ["properties.sC_CasDayL1_b0"]
    },
  "query": {
    "match": {
      "properties.Sauid": 59008199
    }
  },
  "aggs": {
    "Sum sC_CasDayL1_b0": {
      "sum": {
        "field": "properties.sC_CasDayL1_b0"
      }
    }
  }
}

And the response:
{
  "took" : 10,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 69,
      "relation" : "eq"
    },
    "max_score" : 8.2788925,
    "hits" : [
      {
        "_index" : "opendrr_dsra_sim9p0_cascadiainterfacebestfault_indicators_b_v1.4.2",
        "_type" : "_doc",
        "_id" : "Lu1aaoEBHgS-HUNeGgVz",
        "_score" : 8.2788925,
        "_source" : {
          "properties" : {
            "sC_CasDayL1_b0" : 0.4025
          }
        }
      },
      {
        "_index" : "opendrr_dsra_sim9p0_cascadiainterfacebestfault_indicators_b_v1.4.2",
        "_type" : "_doc",
        "_id" : "Le1aaoEBHgS-HUNeGgVz",
        "_score" : 8.2788925,
        "_source" : {
          "properties" : {
            "sC_CasDayL1_b0" : 0.0575
          }
        }
      },
      .........
      .........
      .........
          }
    ]
  },
  "aggregations" : {
    "Sum sC_CasDayL1_b0" : {
      "value" : 57.0
    }
  }
}

Aha! The smoking gun. Now lets manually sum all of the records from the 69 returned documents:

![Screen Shot 2022-08-25 at 3 17 05 PM](https://user-images.githubusercontent.com/7228960/186778493-29daa2d0-157c-43e9-9fe2-3a6e6a59217d.png)

Huh.... so the underlying data is correct but the ElasticSearch 'sum' aggregation is not summing our data correctly 

Ok, so now we know what the issue is. Now, how do we fix the ES sum aggregation...

**Comment by drotheram** [comment]
On further investigation, it appears that many fields originally mapped as 'float' were re-cast to 'long' in the ElasticSearch dump process. If you round the above values down the the nearest integer and sum you'll get 57 which is exactly what the ES Sum aggregation is doing. Even though the values returned from the search query are displayed like float values they are mapped as 'long' type so ES is aggregating them as such.

The fix will be to reload the latest version of ES index dump files with a defined mapping.
